/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package formulario.contato.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FormularioContato service. Represents a row in the &quot;FC_FormularioContato&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>formulario.contato.model.impl.FormularioContatoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>formulario.contato.model.impl.FormularioContatoImpl</code>.
 * </p>
 *
 * @author Eglen
 * @see FormularioContato
 * @generated
 */
@ProviderType
public interface FormularioContatoModel
	extends BaseModel<FormularioContato>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a formulario contato model instance should use the {@link FormularioContato} interface instead.
	 */

	/**
	 * Returns the primary key of this formulario contato.
	 *
	 * @return the primary key of this formulario contato
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this formulario contato.
	 *
	 * @param primaryKey the primary key of this formulario contato
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this formulario contato.
	 *
	 * @return the mvcc version of this formulario contato
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this formulario contato.
	 *
	 * @param mvccVersion the mvcc version of this formulario contato
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this formulario contato.
	 *
	 * @return the uuid of this formulario contato
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this formulario contato.
	 *
	 * @param uuid the uuid of this formulario contato
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the formulario ID of this formulario contato.
	 *
	 * @return the formulario ID of this formulario contato
	 */
	public long getFormularioId();

	/**
	 * Sets the formulario ID of this formulario contato.
	 *
	 * @param formularioId the formulario ID of this formulario contato
	 */
	public void setFormularioId(long formularioId);

	/**
	 * Returns the nome of this formulario contato.
	 *
	 * @return the nome of this formulario contato
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this formulario contato.
	 *
	 * @param nome the nome of this formulario contato
	 */
	public void setNome(String nome);

	/**
	 * Returns the email of this formulario contato.
	 *
	 * @return the email of this formulario contato
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this formulario contato.
	 *
	 * @param email the email of this formulario contato
	 */
	public void setEmail(String email);

	/**
	 * Returns the estado of this formulario contato.
	 *
	 * @return the estado of this formulario contato
	 */
	@AutoEscape
	public String getEstado();

	/**
	 * Sets the estado of this formulario contato.
	 *
	 * @param estado the estado of this formulario contato
	 */
	public void setEstado(String estado);

	/**
	 * Returns the cidade of this formulario contato.
	 *
	 * @return the cidade of this formulario contato
	 */
	@AutoEscape
	public String getCidade();

	/**
	 * Sets the cidade of this formulario contato.
	 *
	 * @param cidade the cidade of this formulario contato
	 */
	public void setCidade(String cidade);

	/**
	 * Returns the mensagem of this formulario contato.
	 *
	 * @return the mensagem of this formulario contato
	 */
	@AutoEscape
	public String getMensagem();

	/**
	 * Sets the mensagem of this formulario contato.
	 *
	 * @param mensagem the mensagem of this formulario contato
	 */
	public void setMensagem(String mensagem);

	/**
	 * Returns the protocolo of this formulario contato.
	 *
	 * @return the protocolo of this formulario contato
	 */
	@AutoEscape
	public String getProtocolo();

	/**
	 * Sets the protocolo of this formulario contato.
	 *
	 * @param protocolo the protocolo of this formulario contato
	 */
	public void setProtocolo(String protocolo);

	/**
	 * Returns the group ID of this formulario contato.
	 *
	 * @return the group ID of this formulario contato
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this formulario contato.
	 *
	 * @param groupId the group ID of this formulario contato
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this formulario contato.
	 *
	 * @return the company ID of this formulario contato
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this formulario contato.
	 *
	 * @param companyId the company ID of this formulario contato
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this formulario contato.
	 *
	 * @return the user ID of this formulario contato
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this formulario contato.
	 *
	 * @param userId the user ID of this formulario contato
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this formulario contato.
	 *
	 * @return the user uuid of this formulario contato
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this formulario contato.
	 *
	 * @param userUuid the user uuid of this formulario contato
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this formulario contato.
	 *
	 * @return the user name of this formulario contato
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this formulario contato.
	 *
	 * @param userName the user name of this formulario contato
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this formulario contato.
	 *
	 * @return the create date of this formulario contato
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this formulario contato.
	 *
	 * @param createDate the create date of this formulario contato
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this formulario contato.
	 *
	 * @return the modified date of this formulario contato
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this formulario contato.
	 *
	 * @param modifiedDate the modified date of this formulario contato
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this formulario contato.
	 *
	 * @return the status of this formulario contato
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this formulario contato.
	 *
	 * @param status the status of this formulario contato
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this formulario contato.
	 *
	 * @return the status by user ID of this formulario contato
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this formulario contato.
	 *
	 * @param statusByUserId the status by user ID of this formulario contato
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this formulario contato.
	 *
	 * @return the status by user uuid of this formulario contato
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this formulario contato.
	 *
	 * @param statusByUserUuid the status by user uuid of this formulario contato
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this formulario contato.
	 *
	 * @return the status by user name of this formulario contato
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this formulario contato.
	 *
	 * @param statusByUserName the status by user name of this formulario contato
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this formulario contato.
	 *
	 * @return the status date of this formulario contato
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this formulario contato.
	 *
	 * @param statusDate the status date of this formulario contato
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this formulario contato is approved.
	 *
	 * @return <code>true</code> if this formulario contato is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this formulario contato is denied.
	 *
	 * @return <code>true</code> if this formulario contato is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this formulario contato is a draft.
	 *
	 * @return <code>true</code> if this formulario contato is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this formulario contato is expired.
	 *
	 * @return <code>true</code> if this formulario contato is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this formulario contato is inactive.
	 *
	 * @return <code>true</code> if this formulario contato is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this formulario contato is incomplete.
	 *
	 * @return <code>true</code> if this formulario contato is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this formulario contato is pending.
	 *
	 * @return <code>true</code> if this formulario contato is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this formulario contato is scheduled.
	 *
	 * @return <code>true</code> if this formulario contato is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}