/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package formulario.contato.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandler;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerRegistryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Criterion;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Disjunction;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.dao.orm.Property;
import com.liferay.portal.kernel.dao.orm.PropertyFactoryUtil;
import com.liferay.portal.kernel.dao.orm.RestrictionsFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import formulario.contato.model.FormularioContato;
import formulario.contato.service.FormularioContatoLocalService;
import formulario.contato.service.persistence.EstadoPersistence;
import formulario.contato.service.persistence.FormularioContatoPersistence;
import formulario.contato.service.persistence.MunicipioPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the formulario contato local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link formulario.contato.service.impl.FormularioContatoLocalServiceImpl}.
 * </p>
 *
 * @author Eglen
 * @see formulario.contato.service.impl.FormularioContatoLocalServiceImpl
 * @generated
 */
public abstract class FormularioContatoLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, FormularioContatoLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>FormularioContatoLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>formulario.contato.service.FormularioContatoLocalServiceUtil</code>.
	 */

	/**
	 * Adds the formulario contato to the database. Also notifies the appropriate model listeners.
	 *
	 * @param formularioContato the formulario contato
	 * @return the formulario contato that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FormularioContato addFormularioContato(
		FormularioContato formularioContato) {

		formularioContato.setNew(true);

		return formularioContatoPersistence.update(formularioContato);
	}

	/**
	 * Creates a new formulario contato with the primary key. Does not add the formulario contato to the database.
	 *
	 * @param formularioId the primary key for the new formulario contato
	 * @return the new formulario contato
	 */
	@Override
	@Transactional(enabled = false)
	public FormularioContato createFormularioContato(long formularioId) {
		return formularioContatoPersistence.create(formularioId);
	}

	/**
	 * Deletes the formulario contato with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param formularioId the primary key of the formulario contato
	 * @return the formulario contato that was removed
	 * @throws PortalException if a formulario contato with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FormularioContato deleteFormularioContato(long formularioId)
		throws PortalException {

		return formularioContatoPersistence.remove(formularioId);
	}

	/**
	 * Deletes the formulario contato from the database. Also notifies the appropriate model listeners.
	 *
	 * @param formularioContato the formulario contato
	 * @return the formulario contato that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FormularioContato deleteFormularioContato(
		FormularioContato formularioContato) {

		return formularioContatoPersistence.remove(formularioContato);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			FormularioContato.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return formularioContatoPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>formulario.contato.model.impl.FormularioContatoModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return formularioContatoPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>formulario.contato.model.impl.FormularioContatoModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return formularioContatoPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return formularioContatoPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return formularioContatoPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public FormularioContato fetchFormularioContato(long formularioId) {
		return formularioContatoPersistence.fetchByPrimaryKey(formularioId);
	}

	/**
	 * Returns the formulario contato matching the UUID and group.
	 *
	 * @param uuid the formulario contato's UUID
	 * @param groupId the primary key of the group
	 * @return the matching formulario contato, or <code>null</code> if a matching formulario contato could not be found
	 */
	@Override
	public FormularioContato fetchFormularioContatoByUuidAndGroupId(
		String uuid, long groupId) {

		return formularioContatoPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the formulario contato with the primary key.
	 *
	 * @param formularioId the primary key of the formulario contato
	 * @return the formulario contato
	 * @throws PortalException if a formulario contato with the primary key could not be found
	 */
	@Override
	public FormularioContato getFormularioContato(long formularioId)
		throws PortalException {

		return formularioContatoPersistence.findByPrimaryKey(formularioId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			formularioContatoLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FormularioContato.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("formularioId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			formularioContatoLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(FormularioContato.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"formularioId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			formularioContatoLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FormularioContato.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("formularioId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					Criterion modifiedDateCriterion =
						portletDataContext.getDateRangeCriteria("modifiedDate");

					Criterion statusDateCriterion =
						portletDataContext.getDateRangeCriteria("statusDate");

					if ((modifiedDateCriterion != null) &&
						(statusDateCriterion != null)) {

						Disjunction disjunction =
							RestrictionsFactoryUtil.disjunction();

						disjunction.add(modifiedDateCriterion);
						disjunction.add(statusDateCriterion);

						dynamicQuery.add(disjunction);
					}

					Property workflowStatusProperty =
						PropertyFactoryUtil.forName("status");

					if (portletDataContext.isInitialPublication()) {
						dynamicQuery.add(
							workflowStatusProperty.ne(
								WorkflowConstants.STATUS_IN_TRASH));
					}
					else {
						StagedModelDataHandler<?> stagedModelDataHandler =
							StagedModelDataHandlerRegistryUtil.
								getStagedModelDataHandler(
									FormularioContato.class.getName());

						dynamicQuery.add(
							workflowStatusProperty.in(
								stagedModelDataHandler.
									getExportableStatuses()));
					}
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<FormularioContato>() {

				@Override
				public void performAction(FormularioContato formularioContato)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, formularioContato);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(FormularioContato.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return formularioContatoLocalService.deleteFormularioContato(
			(FormularioContato)persistedModel);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return formularioContatoPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the formulario contatos matching the UUID and company.
	 *
	 * @param uuid the UUID of the formulario contatos
	 * @param companyId the primary key of the company
	 * @return the matching formulario contatos, or an empty list if no matches were found
	 */
	@Override
	public List<FormularioContato> getFormularioContatosByUuidAndCompanyId(
		String uuid, long companyId) {

		return formularioContatoPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of formulario contatos matching the UUID and company.
	 *
	 * @param uuid the UUID of the formulario contatos
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of formulario contatos
	 * @param end the upper bound of the range of formulario contatos (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching formulario contatos, or an empty list if no matches were found
	 */
	@Override
	public List<FormularioContato> getFormularioContatosByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<FormularioContato> orderByComparator) {

		return formularioContatoPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the formulario contato matching the UUID and group.
	 *
	 * @param uuid the formulario contato's UUID
	 * @param groupId the primary key of the group
	 * @return the matching formulario contato
	 * @throws PortalException if a matching formulario contato could not be found
	 */
	@Override
	public FormularioContato getFormularioContatoByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return formularioContatoPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the formulario contatos.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>formulario.contato.model.impl.FormularioContatoModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of formulario contatos
	 * @param end the upper bound of the range of formulario contatos (not inclusive)
	 * @return the range of formulario contatos
	 */
	@Override
	public List<FormularioContato> getFormularioContatos(int start, int end) {
		return formularioContatoPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of formulario contatos.
	 *
	 * @return the number of formulario contatos
	 */
	@Override
	public int getFormularioContatosCount() {
		return formularioContatoPersistence.countAll();
	}

	/**
	 * Updates the formulario contato in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param formularioContato the formulario contato
	 * @return the formulario contato that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FormularioContato updateFormularioContato(
		FormularioContato formularioContato) {

		return formularioContatoPersistence.update(formularioContato);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			FormularioContatoLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		formularioContatoLocalService = (FormularioContatoLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FormularioContatoLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return FormularioContato.class;
	}

	protected String getModelClassName() {
		return FormularioContato.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				formularioContatoPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected EstadoPersistence estadoPersistence;

	protected FormularioContatoLocalService formularioContatoLocalService;

	@Reference
	protected FormularioContatoPersistence formularioContatoPersistence;

	@Reference
	protected MunicipioPersistence municipioPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}