/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package formulario.contato.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import formulario.contato.model.Estado;
import formulario.contato.model.EstadoModel;
import formulario.contato.model.EstadoSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Estado service. Represents a row in the &quot;FC_Estado&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EstadoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EstadoImpl}.
 * </p>
 *
 * @author Eglen
 * @see EstadoImpl
 * @generated
 */
@JSON(strict = true)
public class EstadoModelImpl
	extends BaseModelImpl<Estado> implements EstadoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a estado model instance should use the <code>Estado</code> interface instead.
	 */
	public static final String TABLE_NAME = "FC_Estado";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"estadoId", Types.BIGINT}, {"nome", Types.VARCHAR},
		{"sigla", Types.VARCHAR}, {"codigo", Types.VARCHAR},
		{"cidade", Types.VARCHAR}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("estadoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nome", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sigla", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("codigo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cidade", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FC_Estado (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,estadoId LONG not null primary key,nome VARCHAR(75) null,sigla VARCHAR(75) null,codigo VARCHAR(75) null,cidade VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table FC_Estado";

	public static final String ORDER_BY_JPQL = " ORDER BY estado.nome DESC";

	public static final String ORDER_BY_SQL = " ORDER BY FC_Estado.nome DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long NOME_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Estado toModel(EstadoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Estado model = new EstadoImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setUuid(soapModel.getUuid());
		model.setEstadoId(soapModel.getEstadoId());
		model.setNome(soapModel.getNome());
		model.setSigla(soapModel.getSigla());
		model.setCodigo(soapModel.getCodigo());
		model.setCidade(soapModel.getCidade());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Estado> toModels(EstadoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Estado> models = new ArrayList<Estado>(soapModels.length);

		for (EstadoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public EstadoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _estadoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEstadoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _estadoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Estado.class;
	}

	@Override
	public String getModelClassName() {
		return Estado.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Estado, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Estado, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Estado, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Estado)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Estado, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Estado, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Estado)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Estado, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Estado, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Estado>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Estado.class.getClassLoader(), Estado.class, ModelWrapper.class);

		try {
			Constructor<Estado> constructor =
				(Constructor<Estado>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Estado, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Estado, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Estado, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Estado, Object>>();
		Map<String, BiConsumer<Estado, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Estado, ?>>();

		attributeGetterFunctions.put("mvccVersion", Estado::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion", (BiConsumer<Estado, Long>)Estado::setMvccVersion);
		attributeGetterFunctions.put("uuid", Estado::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Estado, String>)Estado::setUuid);
		attributeGetterFunctions.put("estadoId", Estado::getEstadoId);
		attributeSetterBiConsumers.put(
			"estadoId", (BiConsumer<Estado, Long>)Estado::setEstadoId);
		attributeGetterFunctions.put("nome", Estado::getNome);
		attributeSetterBiConsumers.put(
			"nome", (BiConsumer<Estado, String>)Estado::setNome);
		attributeGetterFunctions.put("sigla", Estado::getSigla);
		attributeSetterBiConsumers.put(
			"sigla", (BiConsumer<Estado, String>)Estado::setSigla);
		attributeGetterFunctions.put("codigo", Estado::getCodigo);
		attributeSetterBiConsumers.put(
			"codigo", (BiConsumer<Estado, String>)Estado::setCodigo);
		attributeGetterFunctions.put("cidade", Estado::getCidade);
		attributeSetterBiConsumers.put(
			"cidade", (BiConsumer<Estado, String>)Estado::setCidade);
		attributeGetterFunctions.put("groupId", Estado::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Estado, Long>)Estado::setGroupId);
		attributeGetterFunctions.put("companyId", Estado::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Estado, Long>)Estado::setCompanyId);
		attributeGetterFunctions.put("userId", Estado::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Estado, Long>)Estado::setUserId);
		attributeGetterFunctions.put("userName", Estado::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Estado, String>)Estado::setUserName);
		attributeGetterFunctions.put("createDate", Estado::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Estado, Date>)Estado::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Estado::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Estado, Date>)Estado::setModifiedDate);
		attributeGetterFunctions.put("status", Estado::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Estado, Integer>)Estado::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", Estado::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<Estado, Long>)Estado::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", Estado::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<Estado, String>)Estado::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", Estado::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate", (BiConsumer<Estado, Date>)Estado::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getEstadoId() {
		return _estadoId;
	}

	@Override
	public void setEstadoId(long estadoId) {
		_estadoId = estadoId;
	}

	@JSON
	@Override
	public String getNome() {
		if (_nome == null) {
			return "";
		}
		else {
			return _nome;
		}
	}

	@Override
	public void setNome(String nome) {
		_columnBitmask = -1L;

		_nome = nome;
	}

	@JSON
	@Override
	public String getSigla() {
		if (_sigla == null) {
			return "";
		}
		else {
			return _sigla;
		}
	}

	@Override
	public void setSigla(String sigla) {
		_sigla = sigla;
	}

	@JSON
	@Override
	public String getCodigo() {
		if (_codigo == null) {
			return "";
		}
		else {
			return _codigo;
		}
	}

	@Override
	public void setCodigo(String codigo) {
		_codigo = codigo;
	}

	@JSON
	@Override
	public String getCidade() {
		if (_cidade == null) {
			return "";
		}
		else {
			return _cidade;
		}
	}

	@Override
	public void setCidade(String cidade) {
		_cidade = cidade;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Estado.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Estado.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Estado toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Estado>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EstadoImpl estadoImpl = new EstadoImpl();

		estadoImpl.setMvccVersion(getMvccVersion());
		estadoImpl.setUuid(getUuid());
		estadoImpl.setEstadoId(getEstadoId());
		estadoImpl.setNome(getNome());
		estadoImpl.setSigla(getSigla());
		estadoImpl.setCodigo(getCodigo());
		estadoImpl.setCidade(getCidade());
		estadoImpl.setGroupId(getGroupId());
		estadoImpl.setCompanyId(getCompanyId());
		estadoImpl.setUserId(getUserId());
		estadoImpl.setUserName(getUserName());
		estadoImpl.setCreateDate(getCreateDate());
		estadoImpl.setModifiedDate(getModifiedDate());
		estadoImpl.setStatus(getStatus());
		estadoImpl.setStatusByUserId(getStatusByUserId());
		estadoImpl.setStatusByUserName(getStatusByUserName());
		estadoImpl.setStatusDate(getStatusDate());

		estadoImpl.resetOriginalValues();

		return estadoImpl;
	}

	@Override
	public int compareTo(Estado estado) {
		int value = 0;

		value = getNome().compareTo(estado.getNome());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Estado)) {
			return false;
		}

		Estado estado = (Estado)obj;

		long primaryKey = estado.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		EstadoModelImpl estadoModelImpl = this;

		estadoModelImpl._originalUuid = estadoModelImpl._uuid;

		estadoModelImpl._originalGroupId = estadoModelImpl._groupId;

		estadoModelImpl._setOriginalGroupId = false;

		estadoModelImpl._originalCompanyId = estadoModelImpl._companyId;

		estadoModelImpl._setOriginalCompanyId = false;

		estadoModelImpl._setModifiedDate = false;

		estadoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Estado> toCacheModel() {
		EstadoCacheModel estadoCacheModel = new EstadoCacheModel();

		estadoCacheModel.mvccVersion = getMvccVersion();

		estadoCacheModel.uuid = getUuid();

		String uuid = estadoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			estadoCacheModel.uuid = null;
		}

		estadoCacheModel.estadoId = getEstadoId();

		estadoCacheModel.nome = getNome();

		String nome = estadoCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			estadoCacheModel.nome = null;
		}

		estadoCacheModel.sigla = getSigla();

		String sigla = estadoCacheModel.sigla;

		if ((sigla != null) && (sigla.length() == 0)) {
			estadoCacheModel.sigla = null;
		}

		estadoCacheModel.codigo = getCodigo();

		String codigo = estadoCacheModel.codigo;

		if ((codigo != null) && (codigo.length() == 0)) {
			estadoCacheModel.codigo = null;
		}

		estadoCacheModel.cidade = getCidade();

		String cidade = estadoCacheModel.cidade;

		if ((cidade != null) && (cidade.length() == 0)) {
			estadoCacheModel.cidade = null;
		}

		estadoCacheModel.groupId = getGroupId();

		estadoCacheModel.companyId = getCompanyId();

		estadoCacheModel.userId = getUserId();

		estadoCacheModel.userName = getUserName();

		String userName = estadoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			estadoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			estadoCacheModel.createDate = createDate.getTime();
		}
		else {
			estadoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			estadoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			estadoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		estadoCacheModel.status = getStatus();

		estadoCacheModel.statusByUserId = getStatusByUserId();

		estadoCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = estadoCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			estadoCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			estadoCacheModel.statusDate = statusDate.getTime();
		}
		else {
			estadoCacheModel.statusDate = Long.MIN_VALUE;
		}

		return estadoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Estado, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Estado, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Estado, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Estado)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Estado, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Estado, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Estado, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Estado)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Estado>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private String _uuid;
	private String _originalUuid;
	private long _estadoId;
	private String _nome;
	private String _sigla;
	private String _codigo;
	private String _cidade;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _columnBitmask;
	private Estado _escapedModel;

}