/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package formulario.contato.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import formulario.contato.model.FormularioContato;
import formulario.contato.model.FormularioContatoModel;
import formulario.contato.model.FormularioContatoSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FormularioContato service. Represents a row in the &quot;FC_FormularioContato&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FormularioContatoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FormularioContatoImpl}.
 * </p>
 *
 * @author Eglen
 * @see FormularioContatoImpl
 * @generated
 */
@JSON(strict = true)
public class FormularioContatoModelImpl
	extends BaseModelImpl<FormularioContato> implements FormularioContatoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a formulario contato model instance should use the <code>FormularioContato</code> interface instead.
	 */
	public static final String TABLE_NAME = "FC_FormularioContato";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"formularioId", Types.BIGINT}, {"nome", Types.VARCHAR},
		{"email", Types.VARCHAR}, {"estado", Types.VARCHAR},
		{"cidade", Types.VARCHAR}, {"mensagem", Types.VARCHAR},
		{"protocolo", Types.VARCHAR}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("formularioId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nome", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("estado", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cidade", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mensagem", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("protocolo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FC_FormularioContato (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,formularioId LONG not null primary key,nome VARCHAR(75) null,email VARCHAR(75) null,estado VARCHAR(75) null,cidade VARCHAR(75) null,mensagem VARCHAR(75) null,protocolo VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table FC_FormularioContato";

	public static final String ORDER_BY_JPQL =
		" ORDER BY formularioContato.formularioId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FC_FormularioContato.formularioId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long FORMULARIOID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FormularioContato toModel(FormularioContatoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FormularioContato model = new FormularioContatoImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setUuid(soapModel.getUuid());
		model.setFormularioId(soapModel.getFormularioId());
		model.setNome(soapModel.getNome());
		model.setEmail(soapModel.getEmail());
		model.setEstado(soapModel.getEstado());
		model.setCidade(soapModel.getCidade());
		model.setMensagem(soapModel.getMensagem());
		model.setProtocolo(soapModel.getProtocolo());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FormularioContato> toModels(
		FormularioContatoSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<FormularioContato> models = new ArrayList<FormularioContato>(
			soapModels.length);

		for (FormularioContatoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public FormularioContatoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _formularioId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFormularioId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _formularioId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FormularioContato.class;
	}

	@Override
	public String getModelClassName() {
		return FormularioContato.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FormularioContato, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FormularioContato, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FormularioContato, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FormularioContato)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FormularioContato, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FormularioContato, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FormularioContato)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FormularioContato, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FormularioContato, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, FormularioContato>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			FormularioContato.class.getClassLoader(), FormularioContato.class,
			ModelWrapper.class);

		try {
			Constructor<FormularioContato> constructor =
				(Constructor<FormularioContato>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<FormularioContato, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<FormularioContato, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<FormularioContato, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<FormularioContato, Object>>();
		Map<String, BiConsumer<FormularioContato, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<FormularioContato, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", FormularioContato::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<FormularioContato, Long>)
				FormularioContato::setMvccVersion);
		attributeGetterFunctions.put("uuid", FormularioContato::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<FormularioContato, String>)FormularioContato::setUuid);
		attributeGetterFunctions.put(
			"formularioId", FormularioContato::getFormularioId);
		attributeSetterBiConsumers.put(
			"formularioId",
			(BiConsumer<FormularioContato, Long>)
				FormularioContato::setFormularioId);
		attributeGetterFunctions.put("nome", FormularioContato::getNome);
		attributeSetterBiConsumers.put(
			"nome",
			(BiConsumer<FormularioContato, String>)FormularioContato::setNome);
		attributeGetterFunctions.put("email", FormularioContato::getEmail);
		attributeSetterBiConsumers.put(
			"email",
			(BiConsumer<FormularioContato, String>)FormularioContato::setEmail);
		attributeGetterFunctions.put("estado", FormularioContato::getEstado);
		attributeSetterBiConsumers.put(
			"estado",
			(BiConsumer<FormularioContato, String>)
				FormularioContato::setEstado);
		attributeGetterFunctions.put("cidade", FormularioContato::getCidade);
		attributeSetterBiConsumers.put(
			"cidade",
			(BiConsumer<FormularioContato, String>)
				FormularioContato::setCidade);
		attributeGetterFunctions.put(
			"mensagem", FormularioContato::getMensagem);
		attributeSetterBiConsumers.put(
			"mensagem",
			(BiConsumer<FormularioContato, String>)
				FormularioContato::setMensagem);
		attributeGetterFunctions.put(
			"protocolo", FormularioContato::getProtocolo);
		attributeSetterBiConsumers.put(
			"protocolo",
			(BiConsumer<FormularioContato, String>)
				FormularioContato::setProtocolo);
		attributeGetterFunctions.put("groupId", FormularioContato::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<FormularioContato, Long>)FormularioContato::setGroupId);
		attributeGetterFunctions.put(
			"companyId", FormularioContato::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<FormularioContato, Long>)
				FormularioContato::setCompanyId);
		attributeGetterFunctions.put("userId", FormularioContato::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<FormularioContato, Long>)FormularioContato::setUserId);
		attributeGetterFunctions.put(
			"userName", FormularioContato::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<FormularioContato, String>)
				FormularioContato::setUserName);
		attributeGetterFunctions.put(
			"createDate", FormularioContato::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<FormularioContato, Date>)
				FormularioContato::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", FormularioContato::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<FormularioContato, Date>)
				FormularioContato::setModifiedDate);
		attributeGetterFunctions.put("status", FormularioContato::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<FormularioContato, Integer>)
				FormularioContato::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", FormularioContato::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<FormularioContato, Long>)
				FormularioContato::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", FormularioContato::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<FormularioContato, String>)
				FormularioContato::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", FormularioContato::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<FormularioContato, Date>)
				FormularioContato::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getFormularioId() {
		return _formularioId;
	}

	@Override
	public void setFormularioId(long formularioId) {
		_formularioId = formularioId;
	}

	@JSON
	@Override
	public String getNome() {
		if (_nome == null) {
			return "";
		}
		else {
			return _nome;
		}
	}

	@Override
	public void setNome(String nome) {
		_nome = nome;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_email = email;
	}

	@JSON
	@Override
	public String getEstado() {
		if (_estado == null) {
			return "";
		}
		else {
			return _estado;
		}
	}

	@Override
	public void setEstado(String estado) {
		_estado = estado;
	}

	@JSON
	@Override
	public String getCidade() {
		if (_cidade == null) {
			return "";
		}
		else {
			return _cidade;
		}
	}

	@Override
	public void setCidade(String cidade) {
		_cidade = cidade;
	}

	@JSON
	@Override
	public String getMensagem() {
		if (_mensagem == null) {
			return "";
		}
		else {
			return _mensagem;
		}
	}

	@Override
	public void setMensagem(String mensagem) {
		_mensagem = mensagem;
	}

	@JSON
	@Override
	public String getProtocolo() {
		if (_protocolo == null) {
			return "";
		}
		else {
			return _protocolo;
		}
	}

	@Override
	public void setProtocolo(String protocolo) {
		_protocolo = protocolo;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(FormularioContato.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FormularioContato.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FormularioContato toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FormularioContato>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FormularioContatoImpl formularioContatoImpl =
			new FormularioContatoImpl();

		formularioContatoImpl.setMvccVersion(getMvccVersion());
		formularioContatoImpl.setUuid(getUuid());
		formularioContatoImpl.setFormularioId(getFormularioId());
		formularioContatoImpl.setNome(getNome());
		formularioContatoImpl.setEmail(getEmail());
		formularioContatoImpl.setEstado(getEstado());
		formularioContatoImpl.setCidade(getCidade());
		formularioContatoImpl.setMensagem(getMensagem());
		formularioContatoImpl.setProtocolo(getProtocolo());
		formularioContatoImpl.setGroupId(getGroupId());
		formularioContatoImpl.setCompanyId(getCompanyId());
		formularioContatoImpl.setUserId(getUserId());
		formularioContatoImpl.setUserName(getUserName());
		formularioContatoImpl.setCreateDate(getCreateDate());
		formularioContatoImpl.setModifiedDate(getModifiedDate());
		formularioContatoImpl.setStatus(getStatus());
		formularioContatoImpl.setStatusByUserId(getStatusByUserId());
		formularioContatoImpl.setStatusByUserName(getStatusByUserName());
		formularioContatoImpl.setStatusDate(getStatusDate());

		formularioContatoImpl.resetOriginalValues();

		return formularioContatoImpl;
	}

	@Override
	public int compareTo(FormularioContato formularioContato) {
		long primaryKey = formularioContato.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FormularioContato)) {
			return false;
		}

		FormularioContato formularioContato = (FormularioContato)obj;

		long primaryKey = formularioContato.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		FormularioContatoModelImpl formularioContatoModelImpl = this;

		formularioContatoModelImpl._originalUuid =
			formularioContatoModelImpl._uuid;

		formularioContatoModelImpl._originalGroupId =
			formularioContatoModelImpl._groupId;

		formularioContatoModelImpl._setOriginalGroupId = false;

		formularioContatoModelImpl._originalCompanyId =
			formularioContatoModelImpl._companyId;

		formularioContatoModelImpl._setOriginalCompanyId = false;

		formularioContatoModelImpl._setModifiedDate = false;

		formularioContatoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FormularioContato> toCacheModel() {
		FormularioContatoCacheModel formularioContatoCacheModel =
			new FormularioContatoCacheModel();

		formularioContatoCacheModel.mvccVersion = getMvccVersion();

		formularioContatoCacheModel.uuid = getUuid();

		String uuid = formularioContatoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			formularioContatoCacheModel.uuid = null;
		}

		formularioContatoCacheModel.formularioId = getFormularioId();

		formularioContatoCacheModel.nome = getNome();

		String nome = formularioContatoCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			formularioContatoCacheModel.nome = null;
		}

		formularioContatoCacheModel.email = getEmail();

		String email = formularioContatoCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			formularioContatoCacheModel.email = null;
		}

		formularioContatoCacheModel.estado = getEstado();

		String estado = formularioContatoCacheModel.estado;

		if ((estado != null) && (estado.length() == 0)) {
			formularioContatoCacheModel.estado = null;
		}

		formularioContatoCacheModel.cidade = getCidade();

		String cidade = formularioContatoCacheModel.cidade;

		if ((cidade != null) && (cidade.length() == 0)) {
			formularioContatoCacheModel.cidade = null;
		}

		formularioContatoCacheModel.mensagem = getMensagem();

		String mensagem = formularioContatoCacheModel.mensagem;

		if ((mensagem != null) && (mensagem.length() == 0)) {
			formularioContatoCacheModel.mensagem = null;
		}

		formularioContatoCacheModel.protocolo = getProtocolo();

		String protocolo = formularioContatoCacheModel.protocolo;

		if ((protocolo != null) && (protocolo.length() == 0)) {
			formularioContatoCacheModel.protocolo = null;
		}

		formularioContatoCacheModel.groupId = getGroupId();

		formularioContatoCacheModel.companyId = getCompanyId();

		formularioContatoCacheModel.userId = getUserId();

		formularioContatoCacheModel.userName = getUserName();

		String userName = formularioContatoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			formularioContatoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			formularioContatoCacheModel.createDate = createDate.getTime();
		}
		else {
			formularioContatoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			formularioContatoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			formularioContatoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		formularioContatoCacheModel.status = getStatus();

		formularioContatoCacheModel.statusByUserId = getStatusByUserId();

		formularioContatoCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = formularioContatoCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			formularioContatoCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			formularioContatoCacheModel.statusDate = statusDate.getTime();
		}
		else {
			formularioContatoCacheModel.statusDate = Long.MIN_VALUE;
		}

		return formularioContatoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FormularioContato, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FormularioContato, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FormularioContato, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((FormularioContato)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<FormularioContato, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<FormularioContato, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FormularioContato, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((FormularioContato)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FormularioContato>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private String _uuid;
	private String _originalUuid;
	private long _formularioId;
	private String _nome;
	private String _email;
	private String _estado;
	private String _cidade;
	private String _mensagem;
	private String _protocolo;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _columnBitmask;
	private FormularioContato _escapedModel;

}